<?php

use Illuminate\Database\Seeder;

class AuthzInitialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('roles')->insert([
            ['id' => 1, 'name' => 'admin', 'guard_name' => 'web'],
            ['id' => 2, 'name' => 'officer-ii', 'guard_name' => 'web'],
            ['id' => 3, 'name' => 'officer-i', 'guard_name' => 'web'],
            ['id' => 4, 'name' => 'core', 'guard_name' => 'web'],
            ['id' => 5, 'name' => 'member', 'guard_name' => 'web']
        ]);
        
        DB::table('permissions')->insert([
            ['id' => 1, 'name' => 'create-users', 'guard_name' => 'web'],
            ['id' => 2, 'name' => 'read-users', 'guard_name' => 'web'],
            ['id' => 3, 'name' => 'read-users-own', 'guard_name' => 'web'],
            ['id' => 4, 'name' => 'update-users', 'guard_name' => 'web'],
            ['id' => 5, 'name' => 'update-users-own', 'guard_name' => 'web'],
            ['id' => 6, 'name' => 'delete-users', 'guard_name' => 'web'],
            ['id' => 7, 'name' => 'create-events', 'guard_name' => 'web'],
            ['id' => 8, 'name' => 'read-events', 'guard_name' => 'web'],
            ['id' => 9, 'name' => 'update-events', 'guard_name' => 'web'],
            ['id' => 10, 'name' => 'update-events-own', 'guard_name' => 'web'],
            ['id' => 11, 'name' => 'delete-events', 'guard_name' => 'web'],
            ['id' => 12, 'name' => 'create-rsvp', 'guard_name' => 'web'],
            ['id' => 13, 'name' => 'create-rsvp-own', 'guard_name' => 'web'],
            ['id' => 14, 'name' => 'read-rsvps', 'guard_name' => 'web'],
            ['id' => 15, 'name' => 'read-rsvps-own', 'guard_name' => 'web'],
            ['id' => 16, 'name' => 'update-rsvps', 'guard_name' => 'web'],
            ['id' => 17, 'name' => 'update-rsvps-own', 'guard_name' => 'web'],
            ['id' => 18, 'name' => 'delete-rsvps', 'guard_name' => 'web'],
            ['id' => 19, 'name' => 'delete-rsvp-own', 'guard_name' => 'web'],
            ['id' => 20, 'name' => 'create-payments', 'guard_name' => 'web'],
            ['id' => 21, 'name' => 'create-payments-own', 'guard_name' => 'web'],
            ['id' => 22, 'name' => 'read-payments', 'guard_name' => 'web'],
            ['id' => 23, 'name' => 'read-payments-own', 'guard_name' => 'web'],
            ['id' => 24, 'name' => 'update-payments', 'guard_name' => 'web'],
            ['id' => 25, 'name' => 'delete-payments', 'guard_name' => 'web'],
            ['id' => 26, 'name' => 'create-dues-packages', 'guard_name' => 'web'],
            ['id' => 27, 'name' => 'read-dues-packages', 'guard_name' => 'web'],
            ['id' => 28, 'name' => 'update-dues-packages', 'guard_name' => 'web'],
            ['id' => 29, 'name' => 'delete-dues-packages', 'guard_name' => 'web'],
            ['id' => 30, 'name' => 'create-dues-transactions', 'guard_name' => 'web'],
            ['id' => 31, 'name' => 'read-dues-transactions', 'guard_name' => 'web'],
            ['id' => 32, 'name' => 'read-dues-transactions-own', 'guard_name' => 'web'],
            ['id' => 33, 'name' => 'update-dues-transactions', 'guard_name' => 'web'],
            ['id' => 34, 'name' => 'delete-dues-transactions', 'guard_name' => 'web'],
            ['id' => 35, 'name' => 'create-faset-visits', 'guard_name' => 'web'],
            ['id' => 36, 'name' => 'read-faset-visits', 'guard_name' => 'web'],
            ['id' => 37, 'name' => 'read-faset-visits-own', 'guard_name' => 'web'],
            ['id' => 38, 'name' => 'update-faset-visits', 'guard_name' => 'web'],
            ['id' => 39, 'name' => 'update-faset-visits-own', 'guard_name' => 'web'],
            ['id' => 40, 'name' => 'delete-faset-visits', 'guard_name' => 'web'],
            ['id' => 41, 'name' => 'delete-faset-visits-own', 'guard_name' => 'web'],
            ['id' => 42, 'name' => 'send-notifications', 'guard_name' => 'web'],
        ]);
        
        DB::table('role_has_permissions')->insert([
            //Admin gets everything
            ['permission_id' => '1', 'role_id' => '1'],
            ['permission_id' => '2', 'role_id' => '1'],
            ['permission_id' => '3', 'role_id' => '1'],
            ['permission_id' => '4', 'role_id' => '1'],
            ['permission_id' => '5', 'role_id' => '1'],
            ['permission_id' => '6', 'role_id' => '1'],
            ['permission_id' => '7', 'role_id' => '1'],
            ['permission_id' => '8', 'role_id' => '1'],
            ['permission_id' => '9', 'role_id' => '1'],
            ['permission_id' => '10', 'role_id' => '1'],
            ['permission_id' => '11', 'role_id' => '1'],
            ['permission_id' => '12', 'role_id' => '1'],
            ['permission_id' => '13', 'role_id' => '1'],
            ['permission_id' => '14', 'role_id' => '1'],
            ['permission_id' => '15', 'role_id' => '1'],
            ['permission_id' => '16', 'role_id' => '1'],
            ['permission_id' => '17', 'role_id' => '1'],
            ['permission_id' => '18', 'role_id' => '1'],
            ['permission_id' => '19', 'role_id' => '1'],
            ['permission_id' => '20', 'role_id' => '1'],
            ['permission_id' => '21', 'role_id' => '1'],
            ['permission_id' => '22', 'role_id' => '1'],
            ['permission_id' => '23', 'role_id' => '1'],
            ['permission_id' => '24', 'role_id' => '1'],
            ['permission_id' => '25', 'role_id' => '1'],
            ['permission_id' => '26', 'role_id' => '1'],
            ['permission_id' => '27', 'role_id' => '1'],
            ['permission_id' => '28', 'role_id' => '1'],
            ['permission_id' => '29', 'role_id' => '1'],
            ['permission_id' => '30', 'role_id' => '1'],
            ['permission_id' => '31', 'role_id' => '1'],
            ['permission_id' => '32', 'role_id' => '1'],
            ['permission_id' => '33', 'role_id' => '1'],
            ['permission_id' => '34', 'role_id' => '1'],
            ['permission_id' => '35', 'role_id' => '1'],
            ['permission_id' => '36', 'role_id' => '1'],
            ['permission_id' => '37', 'role_id' => '1'],
            ['permission_id' => '38', 'role_id' => '1'],
            ['permission_id' => '39', 'role_id' => '1'],
            ['permission_id' => '40', 'role_id' => '1'],
            ['permission_id' => '41', 'role_id' => '1'],
            ['permission_id' => '42', 'role_id' => '1'],
            //Officer II
            ['permission_id' => '2', 'role_id' => '2'],
            ['permission_id' => '3', 'role_id' => '2'],
            ['permission_id' => '4', 'role_id' => '2'],
            ['permission_id' => '5', 'role_id' => '2'],
            ['permission_id' => '7', 'role_id' => '2'],
            ['permission_id' => '8', 'role_id' => '2'],
            ['permission_id' => '9', 'role_id' => '2'],
            ['permission_id' => '10', 'role_id' => '2'],
            ['permission_id' => '11', 'role_id' => '2'],
            ['permission_id' => '13', 'role_id' => '2'],
            ['permission_id' => '14', 'role_id' => '2'],
            ['permission_id' => '15', 'role_id' => '2'],
            ['permission_id' => '16', 'role_id' => '2'],
            ['permission_id' => '17', 'role_id' => '2'],
            ['permission_id' => '18', 'role_id' => '2'],
            ['permission_id' => '19', 'role_id' => '2'],
            ['permission_id' => '20', 'role_id' => '2'],
            ['permission_id' => '22', 'role_id' => '2'],
            ['permission_id' => '23', 'role_id' => '2'],
            ['permission_id' => '26', 'role_id' => '2'],
            ['permission_id' => '27', 'role_id' => '2'],
            ['permission_id' => '28', 'role_id' => '2'],
            ['permission_id' => '30', 'role_id' => '2'],
            ['permission_id' => '31', 'role_id' => '2'],
            ['permission_id' => '32', 'role_id' => '2'],
            ['permission_id' => '33', 'role_id' => '2'],
            ['permission_id' => '35', 'role_id' => '2'],
            ['permission_id' => '36', 'role_id' => '2'],
            ['permission_id' => '37', 'role_id' => '2'],
            ['permission_id' => '38', 'role_id' => '2'],
            ['permission_id' => '39', 'role_id' => '2'],
            //Officer I
            ['permission_id' => '2', 'role_id' => '3'],
            ['permission_id' => '3', 'role_id' => '3'],
            ['permission_id' => '4', 'role_id' => '3'],
            ['permission_id' => '5', 'role_id' => '3'],
            ['permission_id' => '7', 'role_id' => '3'],
            ['permission_id' => '8', 'role_id' => '3'],
            ['permission_id' => '10', 'role_id' => '3'],
            ['permission_id' => '13', 'role_id' => '3'],
            ['permission_id' => '14', 'role_id' => '3'],
            ['permission_id' => '15', 'role_id' => '3'],
            ['permission_id' => '17', 'role_id' => '3'],
            ['permission_id' => '19', 'role_id' => '3'],
            ['permission_id' => '20', 'role_id' => '3'],
            ['permission_id' => '22', 'role_id' => '3'],
            ['permission_id' => '23', 'role_id' => '3'],
            ['permission_id' => '27', 'role_id' => '3'],
            ['permission_id' => '30', 'role_id' => '3'],
            ['permission_id' => '31', 'role_id' => '3'],
            ['permission_id' => '32', 'role_id' => '3'],
            ['permission_id' => '33', 'role_id' => '3'],
            ['permission_id' => '35', 'role_id' => '3'],
            ['permission_id' => '37', 'role_id' => '3'],
            ['permission_id' => '39', 'role_id' => '3'],
            //Core
            ['permission_id' => '3', 'role_id' => '4'],
            ['permission_id' => '5', 'role_id' => '4'],
            ['permission_id' => '7', 'role_id' => '4'],
            ['permission_id' => '8', 'role_id' => '4'],
            ['permission_id' => '10', 'role_id' => '4'],
            ['permission_id' => '13', 'role_id' => '4'],
            ['permission_id' => '15', 'role_id' => '4'],
            ['permission_id' => '17', 'role_id' => '4'],
            ['permission_id' => '19', 'role_id' => '4'],
            ['permission_id' => '23', 'role_id' => '4'],
            ['permission_id' => '27', 'role_id' => '4'],
            ['permission_id' => '30', 'role_id' => '4'],
            ['permission_id' => '32', 'role_id' => '4'],
            ['permission_id' => '35', 'role_id' => '4'],
            ['permission_id' => '37', 'role_id' => '4'],
            ['permission_id' => '39', 'role_id' => '4'],
            //Member
            ['permission_id' => '3', 'role_id' => '5'],
            ['permission_id' => '5', 'role_id' => '5'],
            ['permission_id' => '8', 'role_id' => '5'],
            ['permission_id' => '13', 'role_id' => '5'],
            ['permission_id' => '15', 'role_id' => '5'],
            ['permission_id' => '17', 'role_id' => '5'],
            ['permission_id' => '19', 'role_id' => '5'],
            ['permission_id' => '23', 'role_id' => '5'],
            ['permission_id' => '27', 'role_id' => '5'],
            ['permission_id' => '30', 'role_id' => '5'],
            ['permission_id' => '32', 'role_id' => '5'],
            ['permission_id' => '37', 'role_id' => '5'],
            ['permission_id' => '39', 'role_id' => '5'],
        ]);
    }
}
