pull_request_rules:
  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - status-success=CodeSniffer
      - status-success=Composer Install
      - status-success=Mess Detector
      - status-success=PHPStan
      - status-success=Phan
      - status-success=Syntax
      - status-success=ci/circleci
      - status-success=continuous-integration/styleci/pr
      - status-success=continuous-integration/styleci/push
    actions:
      merge:
        method: merge
      delete_head_branch: {}
