version: "3.8"

services:
  apiary:
    image: robojackets/apiary
    network_mode: host
    environment:
      APP_NAME: Apiary Local
      APP_ENV: local
      APP_DEBUG: true
      APP_LOG_LEVEL: debug
      APP_URL: http://127.0.0.1:8000
      LOG_CHANNEL: stderr
      DB_CONNECTION: sqlite
      DB_SQLITE_LOCATION: /app/storage/quickstart.sqlite
      BROADCAST_CONNECTION: log
      CACHE_STORE: array
      SESSION_DRIVER: file
      QUEUE_DRIVER: sync
      CAS_MASQUERADE: atesting3
      CAS_MASQUERADE_gtGTID: 901234567
      CAS_MASQUERADE_email_primary: developers@robojackets.org
      CAS_MASQUERADE_givenName: Apiary
      CAS_MASQUERADE_sn: Testing
      CAS_MASQUERADE_authnContextClass: mfa-duo
      CAS_MASQUERADE_eduPersonPrimaryAffiliation: student
      CAS_MASQUERADE_eduPersonScopedAffiliation: student@gt
      CAS_HOSTNAME: sso-test.gatech.edu
      CAS_REAL_HOSTS: sso-test.gatech.edu
      CAS_CLIENT_SERVICE: http://127.0.0.1:8000
      JEDI_HOST: null
      JEDI_TOKEN: null
      PASSPORT_PERSONAL_ACCESS_CLIENT_ID: 95b2031a-5593-4d67-909a-ef32ae06a86a
      PASSPORT_PERSONAL_ACCESS_CLIENT_SECRET: cu95hXvaJTe5hsotCHMYDMyycHu83PJIBYffVGHL
      PASSPORT_PUBLIC_KEY: /app/storage/oauth-public.key
      PASSPORT_PRIVATE_KEY: /app/storage/oauth-private.key
      SCOUT_DRIVER: collection
      MAIL_MAILER: log
      BUZZAPI_HOST: apiary-sandbox.robojackets.org
      BUZZAPI_APP_ID: mock
      BUZZAPI_APP_PASSWORD: mock
      FEATURE_DOCUSIGN_MEMBERSHIP_AGREEMENT: false
      FEATURE_ENABLE_WHITEPAGES: false
      FEATURE_SANDBOX_MODE: true
      SANDBOX_USERS: atesting3
    command: >-
      /bin/sh -euxc "export APP_KEY=$$(php artisan key:generate --show --verbose) &&
      php artisan config:validate --no-interaction &&
      php artisan passport:keys --no-interaction --force &&
      touch /app/database/database.sqlite &&
      php artisan migrate --no-interaction &&
      exec php artisan serve"
