name: Auto approve Renovate PRs
on: pull_request

jobs:
  AutoApprove:
    if: github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@7782c7e
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
