name: Deactivate Environments

on:
  schedule:
    - cron:  '0 20 * * *'

jobs:
  deploy:
    name: Deactivate Environments
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nomad
        uses: lucasmelin/setup-nomad@v2.0.0

      - name: Exchange GitHub JWT for Nomad token
        uses: mikenomitch/nomad-jwt-auth@v0.1.0
        with:
          url: https://nomad.bcdc.robojackets.net
          jwtGithubAudience: https://nomad.bcdc.robojackets.net
          methodName: GitHub

      - name: Stop test
        env:
          NOMAD_ADDR: https://nomad.bcdc.robojackets.net
        continue-on-error: true
        run: |
          nomad stop apiary-test

      - name: Stop sandbox
        env:
          NOMAD_ADDR: https://nomad.bcdc.robojackets.net
        continue-on-error: true
        run: |
          nomad stop apiary-sandbox
