name: Deploy

on:
  workflow_call:
    inputs:
      image-ref:
        required: true
        type: string
      environment:
        required: true
        type: string
      precompressed-assets:
        required: true
        type: boolean
  workflow_dispatch:
    inputs:
      image-ref:
        required: true
        type: string
      environment:
        required: true
        type: environment
      precompressed-assets:
        required: true
        type: boolean

jobs:
  deploy:
    name: ${{ inputs.environment }}
    environment:
      name: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nomad
        uses: lucasmelin/setup-nomad@v2.0.0

      - name: Exchange GitHub JWT for Nomad token
        uses: mikenomitch/nomad-jwt-auth@v0.1.0
        with:
          url: https://nomad.bcdc.robojackets.net
          jwtGithubAudience: https://nomad.bcdc.robojackets.net
          methodName: GitHub

      - name: Run Nomad
        run: |
          nomad job status
